version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # MQTT 原生协议
      - "9001:9001"  # MQTT over WebSocket
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always